### ISSUE TITLE
LabVIEW 2016 will not Mass Compile.

### ISSUE THREAD

**Issue by Michael-Ward-StandardAero** [JKISoftware/JKI-VI-Tester#1]
![image](https://cloud.githubusercontent.com/assets/26310341/23766705/8b27fc88-04cb-11e7-96d8-7d5ebc830202.png)

This message appears every time the VI Tester is started.
Pressing OK causes the following error.
![image](https://cloud.githubusercontent.com/assets/26310341/23766755/afb40844-04cb-11e7-99b8-8077f9eb81ad.png)

I have tried mass compiling the tool by running the LabVIEW mass compile but this does not remove the startup message or the error.  If I hit cancel it will allow me to run the tool as normal.

The error claims I need the App Builder.  I have the Full Development System for LabVIEW 2016.  I can confirm the application builder module is installed and works.

I have also confirmed that the same problem shows up on at least two other developers machines that use LabVIEW 2016.

I am using version 1.1.2.274-1

**Comment by tmaila** [comment]
I've verified that this bug is present when installing VI Tester using VIPM when VIPM setting **Mass Compile VIs After Package Installation** is turned off. This bug is not present when **Mass Compile VIs After Package Installation** is on. As a workaround uninstall VI Tester. Then turn on Mass Compile VIs After Package Installation for VIPM under Tools -> Options -> General. Now install VI Tester again.

**Comment by Michael-Ward-StandardAero** [comment]
I was not able to use the work around successfully.  The settings for VI package manager by default appear to have Mass compile VIs after package installation turned On.  I've toggled it off and on and in both cases I experience the same problem.  

Currently I can run the mass compile in LabVIEW on the VI's in the addons folder and this speeds up the startup process but I still receive the "nag" message and if I hit OK it crashes.  Currently I can use the tool by hitting cancel each time.

Using VIPM. 2016.0.0 (build 1986).  "Free Edition"

**Comment by Michael-Ward-StandardAero** [comment]
Upgrading to the latest version of VIPM and having mass compile turned on resolved the problem.  Thank you.
