### ISSUE TITLE
Sort Recent Files by time relevance

### ISSUE THREAD

**Issue by kosist** [JKISoftware/JKI-VI-Tester#27]
It would be nice if Recent Files projects list in VI Tester window would be sorted by time relevance, and put on top the last opened projects.

**Comment by jimkring** [comment]
Should be fixed in https://github.com/JKISoftware/JKI-VI-Tester/releases/tag/3.0.0. You can [download the latest version with VIPM](https://resources.jki.net/vi-tester).
