### ISSUE TITLE
Template Tests Should Have Compiled Code Seperated

### ISSUE THREAD

**Issue by JamesMc86** [JKISoftware/JKI-VI-Tester#28]
Right now they don't.

I think the advice nowadays is for everything to for best compatibility with source control.

**Comment by soul4soul** [comment]
Is JKI VI Tester supported on RT targets? Last I remember compiled code separated can't be used on VIs that are being used with LabVIEW RT.

**Comment by jimkring** [comment]
Hey @JamesMc86. This should be fixed in https://github.com/JKISoftware/JKI-VI-Tester/releases/tag/3.0.0. You can [download the latest version with VIPM](https://resources.jki.net/vi-tester).  Please let us know how this works for you..
