### ISSUE TITLE
Dead Links in "VI Tester Getting Started Guide"

### ISSUE THREAD

**Issue by patricjenni** [JKISoftware/JKI-VI-Tester#9]
All hyperlinks in https://github.com/JKISoftware/JKI-VI-Tester/wiki/VI-Tester-Getting-Started-Guide linking to http://forums.jkisoft.com/ are dead.
It would be nice if these resources could be made available again, making it easier to get started with VI Tester.

**Comment by jimkring** [comment]
Thanks @patricjenni. The links should be working now. We just did a major upgrade of the forums.
